name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Or master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # ------------------ JOB 1: Build the documentation ------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]

      - name: Build Sphinx documentation
        run: sphinx-build -b html docs/source docs/build/html

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  # ------------------ JOB 2: Deploy the documentation ------------------
  deploy:
    # This job requires the 'build' job to succeed first
    needs: build
    
    # Grant permissions for the deployment
    permissions:
      pages: write
      id-token: write
    
    # This environment is managed by GitHub
    environment:
      name: github-pages
      url: ${{ https://yuewang996.github.io/bard/ }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4